name = "ider-order-system"
compatibility_date = "2025-01-01"
pages_build_output_dir = "pages-frontend"

[[d1_databases]]
binding = "DB"
database_name = "ider-orders"
database_id = "9fd8cb75-d10e-4cf3-a0e0-3681e5a59ae8"

[vars]
ENVIRONMENT = "production"
SITE_NAME = "艾德尔修仙工单平台"
CORS_ORIGIN = ""
