name = "ider-order-system"
main = "worker/index.js"
compatibility_date = "2025-01-01"
workers_dev = true

routes = [
  { pattern = "ider-order-system.sifangzhiji.workers.dev/*", zone_id = "", custom_domain = false }
]

[[d1_databases]]
binding = "DB"
database_name = "ider-orders"
database_id = "9fd8cb75-d10e-4cf3-a0e0-3681e5a59ae8"
migrations_dir = "migrations"

[vars]
API_KEY = ""
ENVIRONMENT = "production"
SITE_NAME = "艾德尔修仙工单平台"

[env.dev]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }
